-- Allergen taxonomy seed.
--
-- DESIGN NOTE -- why ingredient-text matching is deliberately narrow:
--
-- Upstream's "Contains:" line is authoritative for the 18 allergens in its own
-- vocabulary (verified: the item-grid trait icons and the label's Contains:
-- list agree exactly, 28/28 across 10 venues). Re-deriving milk/eggs/soy from
-- ingredient prose would add false positives and no information.
--
-- So ingredient matching runs ONLY where upstream gives us nothing:
--   1. resolving a group to a species  (Contains: "Tree Nuts" -> MACADAMIA NUTS)
--   2. allergens outside upstream's vocabulary (mustard, celery, lupin)
--
-- That is also why `covered_by_trait_vocabulary` exists: for those 18, the
-- absence of a trait icon is weak evidence of absence. For everything else it
-- is no evidence at all, and verdict.ts must return `unknown`.

INSERT INTO allergen (id, slug, label, parent_id, kind, covered_by_trait_vocabulary, sort) VALUES
  (1, 'milk', 'Milk', NULL, 'leaf', 1, 1),
  (2, 'eggs', 'Eggs', NULL, 'leaf', 1, 2),
  (3, 'peanuts', 'Peanuts', NULL, 'leaf', 1, 3),
  (4, 'soy', 'Soy', NULL, 'leaf', 1, 4),
  (5, 'sesame', 'Sesame', NULL, 'leaf', 1, 5),
  (6, 'corn', 'Corn', NULL, 'leaf', 1, 6),
  (7, 'coconut', 'Coconut', NULL, 'leaf', 1, 7),
  (8, 'sulfites', 'Sulfites', NULL, 'leaf', 1, 8),
  (9, 'msg', 'MSG', NULL, 'leaf', 1, 9),
  (10, 'gelatin', 'Gelatin', NULL, 'leaf', 1, 10),
  (11, 'alcohol', 'Alcohol', NULL, 'leaf', 1, 11),
  (12, 'red-dye', 'Red Dye', NULL, 'leaf', 1, 12),
  (13, 'pork', 'Pork', NULL, 'leaf', 1, 13),
  (14, 'tree-nuts', 'Tree Nuts', NULL, 'group', 1, 14),
  (15, 'almond', 'Almond', 14, 'leaf', 0, 15),
  (16, 'walnut', 'Walnut', 14, 'leaf', 0, 16),
  (17, 'pecan', 'Pecan', 14, 'leaf', 0, 17),
  (18, 'cashew', 'Cashew', 14, 'leaf', 0, 18),
  (19, 'pistachio', 'Pistachio', 14, 'leaf', 0, 19),
  (20, 'hazelnut', 'Hazelnut', 14, 'leaf', 0, 20),
  (21, 'macadamia', 'Macadamia', 14, 'leaf', 0, 21),
  (22, 'brazil-nut', 'Brazil Nut', 14, 'leaf', 0, 22),
  (23, 'pine-nut', 'Pine Nut', 14, 'leaf', 0, 23),
  (24, 'chestnut', 'Chestnut', 14, 'leaf', 0, 24),
  (25, 'fish', 'Fish', NULL, 'group', 1, 25),
  (26, 'salmon', 'Salmon', 25, 'leaf', 0, 26),
  (27, 'tuna', 'Tuna', 25, 'leaf', 0, 27),
  (28, 'cod', 'Cod', 25, 'leaf', 0, 28),
  (29, 'tilapia', 'Tilapia', 25, 'leaf', 0, 29),
  (30, 'pollock', 'Pollock', 25, 'leaf', 0, 30),
  (31, 'anchovy', 'Anchovy', 25, 'leaf', 0, 31),
  (32, 'shellfish', 'Shellfish', NULL, 'group', 1, 32),
  (33, 'crustacean', 'Crustacean', 32, 'group', 0, 33),
  (34, 'shrimp', 'Shrimp', 33, 'leaf', 0, 34),
  (35, 'crab', 'Crab', 33, 'leaf', 0, 35),
  (36, 'lobster', 'Lobster', 33, 'leaf', 0, 36),
  (37, 'crawfish', 'Crawfish', 33, 'leaf', 0, 37),
  (38, 'mollusk', 'Mollusk', 32, 'group', 0, 38),
  (39, 'clam', 'Clam', 38, 'leaf', 0, 39),
  (40, 'mussel', 'Mussel', 38, 'leaf', 0, 40),
  (41, 'oyster', 'Oyster', 38, 'leaf', 0, 41),
  (42, 'scallop', 'Scallop', 38, 'leaf', 0, 42),
  (43, 'squid', 'Squid', 38, 'leaf', 0, 43),
  (44, 'octopus', 'Octopus', 38, 'leaf', 0, 44),
  (45, 'gluten-grains', 'Gluten Grains', NULL, 'group', 1, 45),
  (46, 'wheat', 'Wheat', 45, 'leaf', 1, 46),
  (47, 'barley', 'Barley', 45, 'leaf', 0, 47),
  (48, 'rye', 'Rye', 45, 'leaf', 0, 48),
  (49, 'malt', 'Malt', 45, 'leaf', 0, 49),
  (50, 'spelt', 'Spelt', 45, 'leaf', 0, 50),
  (51, 'triticale', 'Triticale', 45, 'leaf', 0, 51),
  (52, 'semolina', 'Semolina', 45, 'leaf', 0, 52),
  (53, 'farro', 'Farro', 45, 'leaf', 0, 53),
  (54, 'mustard', 'Mustard', NULL, 'leaf', 0, 54),
  (55, 'celery', 'Celery', NULL, 'leaf', 0, 55),
  (56, 'lupin', 'Lupin', NULL, 'leaf', 0, 56),
  (57, 'vegan', 'Vegan', NULL, 'diet', 0, 57),
  (58, 'vegetarian', 'Vegetarian', NULL, 'diet', 0, 58),
  (59, 'halal', 'Halal', NULL, 'diet', 0, 59),
  (60, 'kosher', 'Kosher', NULL, 'diet', 0, 60),
  (61, 'jain', 'Jain', NULL, 'diet', 0, 61),
  (62, 'local', 'Local', NULL, 'diet', 0, 62),
  (63, 'sustainable-seafood', 'Sustainable Seafood', NULL, 'diet', 0, 63);

INSERT INTO allergen_alias (allergen_id, alias, match_kind, requires_word_boundary, negative_prefixes) VALUES
  (3, 'peanut', 'name', 1, NULL),
  (5, 'sesame', 'name', 1, NULL),
  (5, 'tahini', 'name', 1, NULL),
  (7, 'coconut', 'name', 1, NULL),
  (13, 'pork', 'name', 1, NULL),
  (13, 'bacon', 'name', 1, NULL),
  (13, 'ham', 'name', 1, NULL),
  (14, 'tree nut', 'ingredient', 1, NULL),
  (14, 'tree nuts', 'ingredient', 1, NULL),
  (14, 'mixed nuts', 'ingredient', 1, NULL),
  (14, 'nut butter', 'ingredient', 1, NULL),
  (14, 'praline', 'ingredient', 1, NULL),
  (14, 'nougat', 'ingredient', 1, NULL),
  (14, 'nut topping', 'ingredient', 1, NULL),
  (15, 'almond', 'ingredient', 1, NULL),
  (15, 'almonds', 'ingredient', 1, NULL),
  (15, 'marzipan', 'ingredient', 1, NULL),
  (15, 'frangipane', 'ingredient', 1, NULL),
  (15, 'almond', 'name', 1, NULL),
  (16, 'walnut', 'ingredient', 1, NULL),
  (16, 'walnuts', 'ingredient', 1, NULL),
  (16, 'walnut', 'name', 1, NULL),
  (17, 'pecan', 'ingredient', 1, NULL),
  (17, 'pecans', 'ingredient', 1, NULL),
  (17, 'pecan', 'name', 1, NULL),
  (18, 'cashew', 'ingredient', 1, NULL),
  (18, 'cashews', 'ingredient', 1, NULL),
  (18, 'cashew', 'name', 1, NULL),
  (19, 'pistachio', 'ingredient', 1, NULL),
  (19, 'pistachios', 'ingredient', 1, NULL),
  (19, 'pistachio', 'name', 1, NULL),
  (20, 'hazelnut', 'ingredient', 1, NULL),
  (20, 'hazelnuts', 'ingredient', 1, NULL),
  (20, 'filbert', 'ingredient', 1, NULL),
  (20, 'filberts', 'ingredient', 1, NULL),
  (20, 'gianduja', 'ingredient', 1, NULL),
  (20, 'hazelnut', 'name', 1, NULL),
  (21, 'macadamia', 'ingredient', 1, NULL),
  (21, 'macadamias', 'ingredient', 1, NULL),
  (21, 'macadamia', 'name', 1, NULL),
  (22, 'brazil nut', 'ingredient', 1, NULL),
  (22, 'brazil nuts', 'ingredient', 1, NULL),
  (22, 'brazil nut', 'name', 1, NULL),
  (23, 'pine nut', 'ingredient', 1, NULL),
  (23, 'pine nuts', 'ingredient', 1, NULL),
  (23, 'pignoli', 'ingredient', 1, NULL),
  (23, 'pine nut', 'name', 1, NULL),
  (24, 'chestnut', 'ingredient', 1, 'water'),
  (24, 'chestnuts', 'ingredient', 1, 'water'),
  (24, 'chestnut', 'name', 1, 'water'),
  (26, 'salmon', 'ingredient', 1, NULL),
  (26, 'salmon', 'name', 1, NULL),
  (27, 'tuna', 'ingredient', 1, NULL),
  (27, 'tuna', 'name', 1, NULL),
  (28, 'cod', 'ingredient', 1, NULL),
  (28, 'codfish', 'ingredient', 1, NULL),
  (28, 'cod', 'name', 1, NULL),
  (29, 'tilapia', 'ingredient', 1, NULL),
  (29, 'tilapia', 'name', 1, NULL),
  (30, 'pollock', 'ingredient', 1, NULL),
  (30, 'pollack', 'ingredient', 1, NULL),
  (30, 'pollock', 'name', 1, NULL),
  (31, 'anchovy', 'ingredient', 1, NULL),
  (31, 'anchovies', 'ingredient', 1, NULL),
  (31, 'worcestershire', 'ingredient', 1, NULL),
  (31, 'anchovy', 'name', 1, NULL),
  (34, 'shrimp', 'ingredient', 1, NULL),
  (34, 'prawn', 'ingredient', 1, NULL),
  (34, 'prawns', 'ingredient', 1, NULL),
  (34, 'shrimp', 'name', 1, NULL),
  (35, 'crab', 'ingredient', 1, NULL),
  (35, 'crabmeat', 'ingredient', 1, NULL),
  (35, 'crab', 'name', 1, NULL),
  (36, 'lobster', 'ingredient', 1, NULL),
  (36, 'lobster', 'name', 1, NULL),
  (37, 'crawfish', 'ingredient', 1, NULL),
  (37, 'crayfish', 'ingredient', 1, NULL),
  (37, 'crawfish', 'name', 1, NULL),
  (39, 'clam', 'ingredient', 1, NULL),
  (39, 'clams', 'ingredient', 1, NULL),
  (39, 'clam', 'name', 1, NULL),
  (40, 'mussel', 'ingredient', 1, NULL),
  (40, 'mussels', 'ingredient', 1, NULL),
  (40, 'mussel', 'name', 1, NULL),
  (41, 'oyster', 'ingredient', 1, NULL),
  (41, 'oysters', 'ingredient', 1, NULL),
  (41, 'oyster', 'name', 1, NULL),
  (42, 'scallop', 'ingredient', 1, NULL),
  (42, 'scallops', 'ingredient', 1, NULL),
  (42, 'scallop', 'name', 1, NULL),
  (43, 'squid', 'ingredient', 1, NULL),
  (43, 'calamari', 'ingredient', 1, NULL),
  (43, 'squid', 'name', 1, NULL),
  (44, 'octopus', 'ingredient', 1, NULL),
  (44, 'octopus', 'name', 1, NULL),
  (47, 'barley', 'ingredient', 1, NULL),
  (47, 'malted barley', 'ingredient', 1, NULL),
  (48, 'rye', 'ingredient', 1, NULL),
  (48, 'rye flour', 'ingredient', 1, NULL),
  (49, 'malt', 'ingredient', 1, NULL),
  (49, 'malt extract', 'ingredient', 1, NULL),
  (49, 'maltodextrin', 'ingredient', 1, NULL),
  (50, 'spelt', 'ingredient', 1, NULL),
  (51, 'triticale', 'ingredient', 1, NULL),
  (52, 'semolina', 'ingredient', 1, NULL),
  (52, 'durum', 'ingredient', 1, NULL),
  (53, 'farro', 'ingredient', 1, NULL),
  (53, 'bulgur', 'ingredient', 1, NULL),
  (53, 'couscous', 'ingredient', 1, NULL),
  (53, 'seitan', 'ingredient', 1, NULL),
  (54, 'mustard', 'ingredient', 1, NULL),
  (54, 'mustard seed', 'ingredient', 1, NULL),
  (54, 'dijon', 'ingredient', 1, NULL),
  (54, 'mustard', 'name', 1, NULL),
  (55, 'celery', 'ingredient', 1, NULL),
  (55, 'celery seed', 'ingredient', 1, NULL),
  (55, 'celeriac', 'ingredient', 1, NULL),
  (55, 'celery', 'name', 1, NULL),
  (56, 'lupin', 'ingredient', 1, NULL),
  (56, 'lupine', 'ingredient', 1, NULL),
  (56, 'lupini', 'ingredient', 1, NULL);
